load(
    "//bazel:sxt_build_system.bzl",
    "sxt_cc_component",
)

sxt_cc_component(
    name = "zero",
    with_test = False,
    deps = [
        "//sxt/field51/type:element",
    ],
)

sxt_cc_component(
    name = "d",
    with_test = False,
    deps = [
        "//sxt/field51/type:element",
    ],
)

sxt_cc_component(
    name = "sqrtm1",
    with_test = False,
    deps = [
        "//sxt/field51/type:element",
    ],
)

sxt_cc_component(
    name = "one",
    with_test = False,
    deps = [
        "//sxt/field51/type:element",
    ],
)

sxt_cc_component(
    name = "invsqrtamd",
    with_test = False,
    deps = [
        "//sxt/field51/type:element",
    ],
)
