load(
    "//bazel:sxt_build_system.bzl",
    "sxt_cc_component",
)

sxt_cc_component(
    name = "cuda_callable",
    with_test = False,
)

sxt_cc_component(
    name = "cuda_warning",
    with_test = False,
)

sxt_cc_component(
    name = "max_devices",
    with_test = False,
)
