load(
    "//bazel:sxt_component.bzl",
    "sxt_cc_component",
)

sxt_cc_component(
    name = "one",
    with_test = False,
    deps = [
        "//sxt/field12/base:constants",
        "//sxt/field12/type:element",
    ],
)

sxt_cc_component(
    name = "zero",
    with_test = False,
    deps = [
        "//sxt/field12/type:element",
    ],
)
