load(
    "//bazel:sxt_component.bzl",
    "sxt_cc_component",
)

sxt_cc_component(
    name = "element_affine",
    impl_deps = [
    ],
    test_deps = [
        "//sxt/base/test:unit_test",
        "//sxt/field12/constant:one",
        "//sxt/field12/constant:zero",
    ],
    deps = [
        "//sxt/field12/type:element",
    ],
)
