load(
    "//bazel:sxt_build_system.bzl",
    "sxt_cc_component",
)

sxt_cc_component(
    name = "max_bits",
    with_test = False,
)

sxt_cc_component(
    name = "zero",
    with_test = False,
    deps = [
        "//sxt/scalar25/type:element",
    ],
)
