load(
    "//bazel:sxt_build_system.bzl",
    "sxt_cc_component",
)

sxt_cc_component(
    name = "one",
    with_test = False,
    deps = [
        "//sxt/fieldgk/base:constants",
        "//sxt/fieldgk/type:element",
    ],
)

sxt_cc_component(
    name = "zero",
    with_test = False,
    deps = [
        "//sxt/fieldgk/type:element",
    ],
)
