load(
    "//bazel:sxt_build_system.bzl",
    "sxt_cc_component",
)

sxt_cc_component(
    name = "field",
    with_test = False,
    deps = [
        "//sxt/base/field:element",
        "//sxt/fieldgk/operation:add",
        "//sxt/fieldgk/operation:mul",
        "//sxt/fieldgk/operation:muladd",
        "//sxt/fieldgk/operation:neg",
        "//sxt/fieldgk/operation:sub",
        "//sxt/fieldgk/type:element",
    ],
)

