load("//bazel:sxt_component.bzl", "sxt_cc_component")

sxt_cc_component(
    name = "test_generators",
    with_test = False,
    deps = [
        "//sxt/base/container:span",
        "//sxt/base/functional:function_ref",
        "//sxt/base/test:unit_test",
        "//sxt/curve21/constant:zero",
        "//sxt/curve21/type:element_p3",
        "//sxt/seqcommit/generator:base_element",
    ],
)
